apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsld
  template:
    metadata:
      labels:
        app: wsld
    spec:
      containers:
      - image: okteto.dev/wsld:latest
        name: wsld
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "jakimfett.com"
        - name: Vless_UUID
          value: "4f23b774-266d-405b-8059-e0bb61970ea5"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "4f23b774-266d-405b-8059-e0bb61970ea5"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "$Share233"
